import type { Coffee } from "./types"

export const coffees: Coffee[] = [
  {
    id: "1",
    name: "Ethiopian Yirgacheffe",
    description:
      "Bright and floral with notes of lemon and tea. A classic single-origin coffee with exceptional clarity.",
    price: 18.99,
    image: "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=400&h=400&fit=crop&crop=center",
    category: "beans",
    roastLevel: "light",
    origin: "Ethiopia",
    brewingMethod: ["Pour Over", "French Press", "Aeropress"],
    stock: 25,
    rating: 4.8,
    reviews: 142,
    isOrganic: true,
    isFairTrade: true,
  },
  {
    id: "2",
    name: "Colombian Supremo",
    description:
      "Rich and balanced with chocolate undertones. A smooth, full-bodied coffee perfect for any time of day.",
    price: 16.99,
    image: "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=400&h=400&fit=crop&crop=center",
    category: "beans",
    roastLevel: "medium",
    origin: "Colombia",
    brewingMethod: ["Drip", "Espresso", "French Press"],
    stock: 30,
    rating: 4.6,
    reviews: 98,
    isOrganic: false,
    isFairTrade: true,
  },
  {
    id: "3",
    name: "Italian Dark Roast",
    description: "Bold and intense with smoky notes. Perfect for espresso and those who love a strong cup.",
    price: 15.99,
    image: "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=400&h=400&fit=crop&crop=center",
    category: "beans",
    roastLevel: "dark",
    origin: "Brazil",
    brewingMethod: ["Espresso", "Moka Pot", "French Press"],
    stock: 20,
    rating: 4.4,
    reviews: 76,
    isOrganic: false,
    isFairTrade: false,
  },
  {
    id: "4",
    name: "House Blend Ground",
    description: "Our signature blend, perfectly ground for drip coffee makers. Smooth and approachable.",
    price: 12.99,
    image: "https://images.unsplash.com/photo-1497935586351-b67a49e012bf?w=400&h=400&fit=crop&crop=center",
    category: "ground",
    roastLevel: "medium",
    origin: "Blend",
    brewingMethod: ["Drip", "Pour Over"],
    stock: 40,
    rating: 4.3,
    reviews: 203,
    isOrganic: false,
    isFairTrade: false,
  },
  {
    id: "5",
    name: "Professional Espresso Machine",
    description: "Semi-automatic espresso machine with 15-bar pressure pump. Perfect for home baristas.",
    price: 299.99,
    image: "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400&h=400&fit=crop&crop=center",
    category: "equipment",
    stock: 8,
    rating: 4.7,
    reviews: 45,
  },
  {
    id: "6",
    name: "Ceramic Pour Over Dripper",
    description: "Handcrafted ceramic dripper for the perfect pour over experience. Includes paper filters.",
    price: 24.99,
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=400&h=400&fit=crop&crop=center",
    category: "equipment",
    stock: 15,
    rating: 4.5,
    reviews: 67,
  },
  {
    id: "7",
    name: "Coffee Bean Storage Canister",
    description: "Airtight stainless steel canister to keep your beans fresh. Holds up to 1 pound of coffee.",
    price: 19.99,
    image: "https://images.unsplash.com/photo-1447933601403-0c6688de566e?w=400&h=400&fit=crop&crop=center",
    category: "accessories",
    stock: 25,
    rating: 4.2,
    reviews: 89,
  },
  {
    id: "8",
    name: "Burr Coffee Grinder",
    description: "Precision burr grinder with 18 grind settings. From coarse for French press to fine for espresso.",
    price: 89.99,
    image: "https://images.unsplash.com/photo-1511537190424-bbbab87ac5eb?w=400&h=400&fit=crop&crop=center",
    category: "equipment",
    stock: 12,
    rating: 4.6,
    reviews: 134,
  },
]

export const categories = [
  { value: "all", label: "All Products" },
  { value: "beans", label: "Coffee Beans" },
  { value: "ground", label: "Ground Coffee" },
  { value: "equipment", label: "Equipment" },
  { value: "accessories", label: "Accessories" },
]

export const roastLevels = [
  { value: "all", label: "All Roasts" },
  { value: "light", label: "Light Roast" },
  { value: "medium", label: "Medium Roast" },
  { value: "dark", label: "Dark Roast" },
]
