apiVersion: v1
kind: Service
metadata:
  name: celebal-deployment-pipeline
  namespace: namespace-workflow-1750150130568
  labels:
    app.kubernetes.io/name: celebal-deployment-pipeline
    kubernetes.azure.com/generator: devhub
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: celebal-deployment-pipeline
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000