name: Docker Image CI

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Docker Login
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: Build the Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/celebal-project:latest ./App
          docker push ${{ secrets.DOCKER_USER }}/celebal-project:latest
