name: Docker Image CI

on:
  workflow_dispatch:  # manual trigger

# on:
#   push:
#     branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
      - name: Build the Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/celebal-project:latest ./App
          docker push ${{ secrets.DOCKER_USER }}/celebal-project:latest
